-- 0010 — Seed RBAC: katalog permission Lampiran C, 7 role bawaan Bab 5, dan
-- matriks role × permission × scope (SDD-DB-10, SDD-05 §4.6, SDD-DB-16).
--
-- Sumber kebenaran: Lampiran C.2 (katalog, 🔒, dan pemilik bawaan — mengikat,
-- PM-06), Bab 5 (role), dan tafsir SDD-03 §4.8 bagi pemilik yang bukan daftar
-- role. tests/integration/rbac-seed.test.ts membandingkan hasil seed ini dengan
-- ketiganya baris per baris: menyunting salah satu tanpa yang lain memerahkannya.
--
-- Idempoten: menjalankan ulang bagian up memulihkan nilai bawaan tanpa
-- menggandakan baris (ON CONFLICT … DO UPDATE).

-- migrate:up

-- 79 permission (Lampiran C.2). `inti` = 🔒 (FR-02.2 A1).
INSERT INTO permissions (kode, modul, aksi, deskripsi, inti) VALUES
    ('user.view', 'User', 'view', 'Melihat daftar & detail pengguna', false),
    ('user.create', 'User', 'create', 'Membuat & mengimpor pengguna', true),
    ('user.update', 'User', 'update', 'Menyunting & mengaktifkan/menonaktifkan', true),
    ('user.reset_password', 'User', 'reset_password', 'Menerbitkan password sementara', true),
    ('user.reset_2fa', 'User', 'reset_2fa', 'Mereset 2FA pengguna lain', true),
    ('role.view', 'Role', 'view', 'Melihat role & matriks permission', false),
    ('role.update', 'Role', 'update', 'Mengubah matriks permission', true),
    ('location.view', 'Lokasi', 'view', 'Melihat pohon lokasi', false),
    ('location.manage', 'Lokasi', 'manage', 'CRUD gedung/area/ruangan', false),
    ('category.manage', 'Kategori', 'manage', 'CRUD kategori aset', false),
    ('asset.view', 'Aset', 'view', 'Melihat katalog & detail aset', false),
    ('asset.view_financial', 'Aset', 'view_financial', 'Melihat nilai & sumber perolehan', false),
    ('asset.create', 'Aset', 'create', 'Membuat & mengimpor aset', false),
    ('asset.update', 'Aset', 'update', 'Menyunting aset & mutasi lokasi', false),
    ('asset.update_condition', 'Aset', 'update_condition', 'Mengubah kondisi aset', false),
    ('asset.deactivate', 'Aset', 'deactivate', 'Menonaktifkan aset (bukan penghapusan formal)', false),
    ('asset.export', 'Aset', 'export', 'Mengekspor daftar aset', false),
    ('asset.qr_print', 'Aset', 'qr_print', 'Mencetak label QR', false),
    ('asset.qr_regenerate', 'Aset', 'qr_regenerate', 'Meregenerasi UUID QR', true),
    ('asset_document.view', 'Dokumen', 'view', 'Melihat & mengunduh dokumen aset', false),
    ('asset_document.manage', 'Dokumen', 'manage', 'Unggah & hapus dokumen aset', false),
    ('reservation.view', 'Reservasi', 'view', 'Melihat kalender & daftar reservasi', false),
    ('reservation.create', 'Reservasi', 'create', 'Mengajukan reservasi', false),
    ('reservation.cancel_own', 'Reservasi', 'cancel_own', 'Membatalkan reservasi sendiri', false),
    ('reservation.cancel_any', 'Reservasi', 'cancel_any', 'Membatalkan reservasi pihak lain', false),
    ('reservation.urgent', 'Reservasi', 'urgent', 'Mengajukan di luar tenggat H-1 (BR-020)', false),
    ('reservation.fixed_schedule', 'Reservasi', 'fixed_schedule', 'Mengelola blokade jadwal tetap ruangan (FR-07.5)', false),
    ('loan.view', 'Peminjaman', 'view', 'Melihat transaksi peminjaman', false),
    ('loan.manage', 'Peminjaman', 'manage', 'Serah terima & pengembalian', false),
    ('loan.direct', 'Peminjaman', 'direct', 'Peminjaman langsung tanpa reservasi', false),
    ('loan.extend', 'Peminjaman', 'extend', 'Mengajukan perpanjangan', false),
    ('fine.view', 'Denda', 'view', 'Melihat denda', false),
    ('fine.manage', 'Denda', 'manage', 'Menandai lunas', false),
    ('fine.waive', 'Denda', 'waive', 'Membebaskan denda berjenis Keterlambatan', false),
    ('fine.waive_compensation', 'Denda', 'waive_compensation', 'Membebaskan kewajiban Ganti Rugi, penuh atau sebagian (BR-028e)', false),
    ('approval_rule.view', 'Approval', 'view', 'Melihat aturan persetujuan', false),
    ('approval_rule.manage', 'Approval', 'manage', 'Membuat & mengubah aturan', true),
    ('approval.view', 'Approval', 'view', 'Melihat riwayat persetujuan', false),
    ('approval.decide', 'Approval', 'decide', 'Menyetujui/menolak pengajuan', false),
    ('approval.delegate', 'Approval', 'delegate', 'Menetapkan approver pengganti', false),
    ('damage.create', 'Kerusakan', 'create', 'Membuat tiket kerusakan', false),
    ('damage.view', 'Kerusakan', 'view', 'Melihat tiket', false),
    ('damage.verify', 'Kerusakan', 'verify', 'Verifikasi/menolak tiket', false),
    ('workorder.view', 'Maintenance', 'view', 'Melihat work order', false),
    ('workorder.create', 'Maintenance', 'create', 'Membuat & menugaskan work order', false),
    ('workorder.execute', 'Maintenance', 'execute', 'Mengeksekusi work order', false),
    ('workorder.verify', 'Maintenance', 'verify', 'Verifikasi & menutup work order', false),
    ('maintenance.manage', 'Maintenance', 'manage', 'Mengelola jadwal preventif', false),
    ('maintenance.view_cost', 'Maintenance', 'view_cost', 'Melihat biaya pemeliharaan', false),
    ('audit.view', 'Opname', 'view', 'Melihat sesi & berita acara', false),
    ('audit.manage', 'Opname', 'manage', 'Membuat & memfinalkan sesi', false),
    ('audit.execute', 'Opname', 'execute', 'Melaksanakan pemindaian opname', false),
    ('audit.approve', 'Opname', 'approve', 'Menyetujui hasil rekonsiliasi', false),
    ('procurement.view', 'Pengadaan', 'view', 'Melihat usulan', false),
    ('procurement.create', 'Pengadaan', 'create', 'Membuat usulan', false),
    ('procurement.approve', 'Pengadaan', 'approve', 'Menyetujui usulan', false),
    ('procurement.receive', 'Pengadaan', 'receive', 'Mencatat penerimaan barang', false),
    ('disposal.view', 'Penghapusan', 'view', 'Melihat usulan & arsip penghapusan', false),
    ('disposal.create', 'Penghapusan', 'create', 'Mengajukan penghapusan', false),
    ('disposal.approve', 'Penghapusan', 'approve', 'Menyetujui penghapusan', false),
    ('disposal.execute', 'Penghapusan', 'execute', 'Mencatat pelaksanaan & menghapuskan', false),
    ('disposal.reinstate', 'Penghapusan', 'reinstate', 'Memulihkan aset terhapus', true),
    ('material.view', 'Bahan', 'view', 'Melihat bahan, saldo, dan kartu stok', false),
    ('material.manage', 'Bahan', 'manage', 'Kelola master bahan & kategori bahan', false),
    ('material.request', 'Bahan', 'request', 'Mengajukan & membatalkan permintaan bahan', false),
    ('material.receive', 'Bahan', 'receive', 'Mencatat penerimaan bahan', false),
    ('material.issue', 'Bahan', 'issue', 'Menyerahkan bahan kepada pemohon', false),
    ('material.adjust', 'Bahan', 'adjust', 'Menyesuaikan saldo dengan alasan wajib', false),
    ('material.qr_print', 'Bahan', 'qr_print', 'Mencetak label QR per jenis bahan', false),
    ('report.view', 'Analitik', 'view', 'Melihat laporan analitik', false),
    ('report.export', 'Analitik', 'export', 'Mengekspor laporan', false),
    ('dashboard.view', 'Dashboard', 'view', 'Mengakses dashboard sesuai role', false),
    ('notification.manage_own', 'Notifikasi', 'manage_own', 'Mengelola notifikasi & preferensi sendiri', false),
    ('activity_log.view', 'Log', 'view', 'Menelusuri activity log', true),
    ('activity_log.export', 'Log', 'export', 'Mengekspor activity log', true),
    ('chat.use', 'Chatbot', 'use', 'Menggunakan chatbot', false),
    ('chat.monitor', 'Chatbot', 'monitor', 'Melihat metrik agregat chatbot', false),
    ('setting.view', 'Sistem', 'view', 'Melihat parameter sistem', false),
    ('setting.manage', 'Sistem', 'manage', 'Mengubah parameter sistem', true)
ON CONFLICT (kode) DO UPDATE
    SET modul     = EXCLUDED.modul,
        aksi      = EXCLUDED.aksi,
        deskripsi = EXCLUDED.deskripsi,
        inti      = EXCLUDED.inti;

-- 7 role bawaan (Bab 5). Seluruhnya is_system: tidak dapat dihapus sebagai role
-- kustom (FR-02.2 A3).
INSERT INTO roles (kode, nama, deskripsi, is_system) VALUES
    ('R-01', 'Administrator', 'Pemilik sistem, akses penuh ke seluruh modul dan konfigurasi', true),
    ('R-02', 'Petugas Sarana Prasarana', 'Pengelola operasional aset sehari-hari', true),
    ('R-03', 'Pimpinan Sekolah', 'Kepala Sekolah & Wakasek Sarpras', true),
    ('R-04', 'Teknisi', 'Pelaksana perbaikan & pemeliharaan internal', true),
    ('R-05', 'Guru', 'Tenaga pendidik', true),
    ('R-06', 'Staf / Tata Usaha', 'Tenaga kependidikan', true),
    ('R-07', 'Siswa / OSIS', 'Peserta didik dengan akun terbatas', true)
ON CONFLICT (kode) DO UPDATE
    SET nama      = EXCLUDED.nama,
        deskripsi = EXCLUDED.deskripsi,
        is_system = EXCLUDED.is_system;

-- Matriks bawaan. Dirujuk lewat KODE, bukan id: id bigserial berbeda antar-
-- lingkungan. Scope: anotasi Lampiran C atau tafsir SDD-03 §4.8; tanpa keduanya ALL.
INSERT INTO role_permissions (role_id, permission_id, scope)
SELECT r.id, p.id, m.scope::permission_scope
  FROM (VALUES
        ('R-01', 'user.view', 'ALL'),
        ('R-02', 'user.view', 'ALL'),
        ('R-03', 'user.view', 'ALL'),
        ('R-01', 'user.create', 'ALL'),
        ('R-01', 'user.update', 'ALL'),
        ('R-01', 'user.reset_password', 'ALL'),
        ('R-01', 'user.reset_2fa', 'ALL'),
        ('R-01', 'role.view', 'ALL'),
        ('R-03', 'role.view', 'ALL'),
        ('R-01', 'role.update', 'ALL'),
        ('R-01', 'location.view', 'ALL'),
        ('R-02', 'location.view', 'ALL'),
        ('R-03', 'location.view', 'ALL'),
        ('R-04', 'location.view', 'ALL'),
        ('R-05', 'location.view', 'ALL'),
        ('R-06', 'location.view', 'ALL'),
        ('R-01', 'location.manage', 'ALL'),
        ('R-02', 'location.manage', 'ALL'),
        ('R-01', 'category.manage', 'ALL'),
        ('R-02', 'category.manage', 'ALL'),
        ('R-01', 'asset.view', 'ALL'),
        ('R-02', 'asset.view', 'ALL'),
        ('R-03', 'asset.view', 'ALL'),
        ('R-04', 'asset.view', 'ALL'),
        ('R-05', 'asset.view', 'ALL'),
        ('R-06', 'asset.view', 'ALL'),
        ('R-07', 'asset.view', 'RESTRICTED'),
        ('R-01', 'asset.view_financial', 'ALL'),
        ('R-02', 'asset.view_financial', 'ALL'),
        ('R-03', 'asset.view_financial', 'ALL'),
        ('R-01', 'asset.create', 'ALL'),
        ('R-02', 'asset.create', 'ALL'),
        ('R-01', 'asset.update', 'ALL'),
        ('R-02', 'asset.update', 'ALL'),
        ('R-01', 'asset.update_condition', 'ALL'),
        ('R-02', 'asset.update_condition', 'ALL'),
        ('R-04', 'asset.update_condition', 'ASSIGNED'),
        ('R-01', 'asset.deactivate', 'ALL'),
        ('R-02', 'asset.deactivate', 'ALL'),
        ('R-01', 'asset.export', 'ALL'),
        ('R-02', 'asset.export', 'ALL'),
        ('R-03', 'asset.export', 'ALL'),
        ('R-01', 'asset.qr_print', 'ALL'),
        ('R-02', 'asset.qr_print', 'ALL'),
        ('R-01', 'asset.qr_regenerate', 'ALL'),
        ('R-01', 'asset_document.view', 'ALL'),
        ('R-02', 'asset_document.view', 'ALL'),
        ('R-03', 'asset_document.view', 'ALL'),
        ('R-04', 'asset_document.view', 'ALL'),
        ('R-05', 'asset_document.view', 'ALL'),
        ('R-06', 'asset_document.view', 'ALL'),
        ('R-01', 'asset_document.manage', 'ALL'),
        ('R-02', 'asset_document.manage', 'ALL'),
        ('R-01', 'reservation.view', 'ALL'),
        ('R-02', 'reservation.view', 'ALL'),
        ('R-03', 'reservation.view', 'ALL'),
        ('R-04', 'reservation.view', 'ALL'),
        ('R-05', 'reservation.view', 'ALL'),
        ('R-06', 'reservation.view', 'ALL'),
        ('R-07', 'reservation.view', 'RESTRICTED'),
        ('R-01', 'reservation.create', 'ALL'),
        ('R-02', 'reservation.create', 'ALL'),
        ('R-05', 'reservation.create', 'ALL'),
        ('R-06', 'reservation.create', 'ALL'),
        ('R-07', 'reservation.create', 'ALL'),
        ('R-01', 'reservation.cancel_own', 'ALL'),
        ('R-02', 'reservation.cancel_own', 'ALL'),
        ('R-05', 'reservation.cancel_own', 'ALL'),
        ('R-06', 'reservation.cancel_own', 'ALL'),
        ('R-07', 'reservation.cancel_own', 'ALL'),
        ('R-01', 'reservation.cancel_any', 'ALL'),
        ('R-02', 'reservation.cancel_any', 'ALL'),
        ('R-01', 'reservation.urgent', 'ALL'),
        ('R-02', 'reservation.urgent', 'ALL'),
        ('R-01', 'reservation.fixed_schedule', 'ALL'),
        ('R-02', 'reservation.fixed_schedule', 'ALL'),
        ('R-01', 'loan.view', 'ALL'),
        ('R-02', 'loan.view', 'ALL'),
        ('R-03', 'loan.view', 'ALL'),
        ('R-05', 'loan.view', 'OWN'),
        ('R-06', 'loan.view', 'OWN'),
        ('R-07', 'loan.view', 'OWN'),
        ('R-01', 'loan.manage', 'ALL'),
        ('R-02', 'loan.manage', 'ALL'),
        ('R-01', 'loan.direct', 'ALL'),
        ('R-02', 'loan.direct', 'ALL'),
        ('R-02', 'loan.extend', 'ALL'),
        ('R-05', 'loan.extend', 'OWN'),
        ('R-06', 'loan.extend', 'OWN'),
        ('R-07', 'loan.extend', 'OWN'),
        ('R-01', 'fine.view', 'ALL'),
        ('R-02', 'fine.view', 'ALL'),
        ('R-03', 'fine.view', 'ALL'),
        ('R-05', 'fine.view', 'OWN'),
        ('R-06', 'fine.view', 'OWN'),
        ('R-07', 'fine.view', 'OWN'),
        ('R-01', 'fine.manage', 'ALL'),
        ('R-02', 'fine.manage', 'ALL'),
        ('R-01', 'fine.waive', 'ALL'),
        ('R-02', 'fine.waive', 'ALL'),
        ('R-03', 'fine.waive_compensation', 'ALL'),
        ('R-01', 'approval_rule.view', 'ALL'),
        ('R-03', 'approval_rule.view', 'ALL'),
        ('R-01', 'approval_rule.manage', 'ALL'),
        ('R-01', 'approval.view', 'ALL'),
        ('R-02', 'approval.view', 'ALL'),
        ('R-03', 'approval.view', 'ALL'),
        ('R-05', 'approval.view', 'OWN'),
        ('R-06', 'approval.view', 'OWN'),
        ('R-07', 'approval.view', 'OWN'),
        ('R-01', 'approval.decide', 'ALL'),
        ('R-02', 'approval.decide', 'ALL'),
        ('R-03', 'approval.decide', 'ALL'),
        ('R-01', 'approval.delegate', 'ALL'),
        ('R-02', 'approval.delegate', 'ALL'),
        ('R-03', 'approval.delegate', 'ALL'),
        ('R-01', 'damage.create', 'ALL'),
        ('R-02', 'damage.create', 'ALL'),
        ('R-03', 'damage.create', 'ALL'),
        ('R-04', 'damage.create', 'ALL'),
        ('R-05', 'damage.create', 'ALL'),
        ('R-06', 'damage.create', 'ALL'),
        ('R-07', 'damage.create', 'ALL'),
        ('R-01', 'damage.view', 'ALL'),
        ('R-02', 'damage.view', 'ALL'),
        ('R-03', 'damage.view', 'ALL'),
        ('R-04', 'damage.view', 'OWN'),
        ('R-05', 'damage.view', 'OWN'),
        ('R-06', 'damage.view', 'OWN'),
        ('R-07', 'damage.view', 'OWN'),
        ('R-01', 'damage.verify', 'ALL'),
        ('R-02', 'damage.verify', 'ALL'),
        ('R-01', 'workorder.view', 'ALL'),
        ('R-02', 'workorder.view', 'ALL'),
        ('R-03', 'workorder.view', 'ALL'),
        ('R-04', 'workorder.view', 'ASSIGNED'),
        ('R-01', 'workorder.create', 'ALL'),
        ('R-02', 'workorder.create', 'ALL'),
        ('R-04', 'workorder.execute', 'ASSIGNED'),
        ('R-01', 'workorder.verify', 'ALL'),
        ('R-02', 'workorder.verify', 'ALL'),
        ('R-01', 'maintenance.manage', 'ALL'),
        ('R-02', 'maintenance.manage', 'ALL'),
        ('R-01', 'maintenance.view_cost', 'ALL'),
        ('R-02', 'maintenance.view_cost', 'ALL'),
        ('R-03', 'maintenance.view_cost', 'ALL'),
        ('R-04', 'maintenance.view_cost', 'ASSIGNED'),
        ('R-01', 'audit.view', 'ALL'),
        ('R-02', 'audit.view', 'ALL'),
        ('R-03', 'audit.view', 'ALL'),
        ('R-01', 'audit.manage', 'ALL'),
        ('R-02', 'audit.manage', 'ALL'),
        ('R-01', 'audit.execute', 'ALL'),
        ('R-02', 'audit.execute', 'ALL'),
        ('R-03', 'audit.approve', 'ALL'),
        ('R-01', 'procurement.view', 'ALL'),
        ('R-02', 'procurement.view', 'ALL'),
        ('R-03', 'procurement.view', 'ALL'),
        ('R-05', 'procurement.view', 'OWN'),
        ('R-06', 'procurement.view', 'OWN'),
        ('R-01', 'procurement.create', 'ALL'),
        ('R-02', 'procurement.create', 'ALL'),
        ('R-05', 'procurement.create', 'ALL'),
        ('R-06', 'procurement.create', 'ALL'),
        ('R-01', 'procurement.approve', 'ALL'),
        ('R-02', 'procurement.approve', 'ALL'),
        ('R-03', 'procurement.approve', 'ALL'),
        ('R-01', 'procurement.receive', 'ALL'),
        ('R-02', 'procurement.receive', 'ALL'),
        ('R-01', 'disposal.view', 'ALL'),
        ('R-02', 'disposal.view', 'ALL'),
        ('R-03', 'disposal.view', 'ALL'),
        ('R-01', 'disposal.create', 'ALL'),
        ('R-02', 'disposal.create', 'ALL'),
        ('R-03', 'disposal.approve', 'ALL'),
        ('R-01', 'disposal.execute', 'ALL'),
        ('R-02', 'disposal.execute', 'ALL'),
        ('R-01', 'disposal.reinstate', 'ALL'),
        ('R-01', 'material.view', 'ALL'),
        ('R-02', 'material.view', 'ALL'),
        ('R-03', 'material.view', 'ALL'),
        ('R-04', 'material.view', 'ALL'),
        ('R-05', 'material.view', 'ALL'),
        ('R-06', 'material.view', 'ALL'),
        ('R-01', 'material.manage', 'ALL'),
        ('R-02', 'material.manage', 'ALL'),
        ('R-01', 'material.request', 'ALL'),
        ('R-02', 'material.request', 'ALL'),
        ('R-04', 'material.request', 'OWN'),
        ('R-05', 'material.request', 'OWN'),
        ('R-06', 'material.request', 'OWN'),
        ('R-01', 'material.receive', 'ALL'),
        ('R-02', 'material.receive', 'ALL'),
        ('R-01', 'material.issue', 'ALL'),
        ('R-02', 'material.issue', 'ALL'),
        ('R-01', 'material.adjust', 'ALL'),
        ('R-02', 'material.adjust', 'ALL'),
        ('R-01', 'material.qr_print', 'ALL'),
        ('R-02', 'material.qr_print', 'ALL'),
        ('R-01', 'report.view', 'ALL'),
        ('R-02', 'report.view', 'ALL'),
        ('R-03', 'report.view', 'ALL'),
        ('R-01', 'report.export', 'ALL'),
        ('R-02', 'report.export', 'ALL'),
        ('R-03', 'report.export', 'ALL'),
        ('R-01', 'dashboard.view', 'ALL'),
        ('R-02', 'dashboard.view', 'ALL'),
        ('R-03', 'dashboard.view', 'ALL'),
        ('R-04', 'dashboard.view', 'OWN'),
        ('R-05', 'dashboard.view', 'OWN'),
        ('R-06', 'dashboard.view', 'OWN'),
        ('R-07', 'dashboard.view', 'OWN'),
        ('R-01', 'notification.manage_own', 'ALL'),
        ('R-02', 'notification.manage_own', 'ALL'),
        ('R-03', 'notification.manage_own', 'ALL'),
        ('R-04', 'notification.manage_own', 'ALL'),
        ('R-05', 'notification.manage_own', 'ALL'),
        ('R-06', 'notification.manage_own', 'ALL'),
        ('R-07', 'notification.manage_own', 'ALL'),
        ('R-01', 'activity_log.view', 'ALL'),
        ('R-03', 'activity_log.view', 'ALL'),
        ('R-01', 'activity_log.export', 'ALL'),
        ('R-01', 'chat.use', 'ALL'),
        ('R-02', 'chat.use', 'ALL'),
        ('R-03', 'chat.use', 'ALL'),
        ('R-04', 'chat.use', 'ALL'),
        ('R-05', 'chat.use', 'ALL'),
        ('R-06', 'chat.use', 'ALL'),
        ('R-07', 'chat.use', 'RESTRICTED'),
        ('R-01', 'chat.monitor', 'ALL'),
        ('R-03', 'chat.monitor', 'ALL'),
        ('R-01', 'setting.view', 'ALL'),
        ('R-03', 'setting.view', 'ALL'),
        ('R-01', 'setting.manage', 'ALL')
       ) AS m (role_kode, permission_kode, scope)
  JOIN roles r       ON r.kode = m.role_kode
  JOIN permissions p ON p.kode = m.permission_kode
ON CONFLICT (role_id, permission_id) DO UPDATE
    SET scope = EXCLUDED.scope;

-- migrate:down
-- Katalog dan role bawaan seluruhnya milik seed ini. Grant role kustom ikut
-- tercabut karena merujuk katalog yang sama.
DELETE FROM role_permissions;
DELETE FROM roles WHERE is_system;
DELETE FROM permissions;
