// Satu set ikon outline (FOUNDATIONS §8; DSD-09: Lucide, stroke 1,5). Nama berperan —
// komponen tidak memilih ikon mentah, sehingga pasangan ikon status tetap (NFR-AC-06).
// Warna selalu `currentColor` dari token teks/ikon; accent tidak pernah menjadi ikon (DSD-07).

import {
    ArrowRightLeft,
    Bell,
    CalendarCheck,
    CalendarClock,
    CalendarDays,
    ChartColumn,
    ChevronDown,
    CircleAlert,
    CircleCheck,
    CircleDashed,
    CircleX,
    ClipboardCheck,
    ClipboardList,
    Copy,
    FileText,
    FileWarning,
    FlaskConical,
    GitBranch,
    Info,
    KeyRound,
    LayoutDashboard,
    LayoutGrid,
    LogOut,
    MapPin,
    Menu,
    MessageSquare,
    Package,
    PanelLeftClose,
    PanelLeftOpen,
    QrCode,
    Receipt,
    RefreshCw,
    ScanLine,
    ScrollText,
    Settings,
    ShieldOff,
    ShoppingCart,
    SquareCheckBig,
    Tags,
    Trash2,
    TriangleAlert,
    Users,
    WifiOff,
    Wrench,
    X,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

const PETA = {
    sukses: CircleCheck,
    peringatan: TriangleAlert,
    galat: CircleX,
    info: Info,
    menunggu: CircleDashed,
    perhatian: CircleAlert,
    dashboard: LayoutDashboard,
    notifikasi: Bell,
    keluar: LogOut,
    ciutkan: PanelLeftClose,
    bentangkan: PanelLeftOpen,
    muatUlang: RefreshCw,
    salin: Copy,
    tanpaAkses: ShieldOff,
    luring: WifiOff,
    chevron: ChevronDown,
    aset: Package,
    kategori: Tags,
    bahan: FlaskConical,
    lokasi: MapPin,
    qr: QrCode,
    dokumen: FileText,
    pindai: ScanLine,
    kalender: CalendarDays,
    katalog: LayoutGrid,
    reservasi: CalendarCheck,
    peminjaman: ArrowRightLeft,
    denda: Receipt,
    permintaan: ClipboardList,
    persetujuan: SquareCheckBig,
    kerusakan: FileWarning,
    workOrder: Wrench,
    jadwal: CalendarClock,
    opname: ClipboardCheck,
    pengadaan: ShoppingCart,
    penghapusan: Trash2,
    analitik: ChartColumn,
    pengguna: Users,
    kunci: KeyRound,
    aturan: GitBranch,
    pengaturan: Settings,
    log: ScrollText,
    chatbot: MessageSquare,
    menu: Menu,
    tutup: X,
} satisfies Record<string, LucideIcon>;

export type NamaIkon = keyof typeof PETA;

const UKURAN = { sm: "size-icon-sm", md: "size-icon-md", lg: "size-icon-lg" } as const;

/** Dekoratif secara bawaan (`aria-hidden`); ikon tanpa teks pendamping wajib memberi `label`. */
export function Ikon({ nama, ukuran = "md", label }: { readonly nama: NamaIkon; readonly ukuran?: keyof typeof UKURAN; readonly label?: string }) {
    const Komponen = PETA[nama];
    return <Komponen strokeWidth={1.5} className={`${UKURAN[ukuran]} shrink-0`} aria-hidden={label === undefined ? true : undefined} aria-label={label} role={label === undefined ? undefined : "img"} />;
}
